name: Upload download

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download txt result for job 1
        uses: actions/download-artifact@v1
        with:
          name: text
      - name: Download report for job 1
        uses: actions/download-artifact@v1
        with:
          name: report
      - name: Print the final result
        shell: bash
        run: |
          value=`cat text.txt`
          echo The result is $value
      - name: Print the final result
        shell: bash
        run: |
          cd report && ls
