name: Upload download

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Upload txt result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: text
          path: text.txt
      - name: Upload folder report for job 1
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: report
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v1
      - name: Download txt result for job 1
        uses: actions/download-artifact@v1
        with:
          name: text
      - name: Print the final result
        shell: bash
        run: |
          value=`cat text.txt`
          echo The result is $value
  job3:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v1
      - name: find path
        run: |
          ls
          cd ./.github/
      - name: call yml
        uses: ./.github/actions/my-action
